apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  username: root
  mongodb.conf: |
    storage:
      dbPath: /data/db
    net:
      bindIp: 0.0.0.0
      port: 27017
    replication:
      replSetName: rs0
